CREATE_BOOK_HOTEL = """ This endpoint create boocking """
UPDATE_BOOK_HOTEL = """ This endpoint update booking hotel """
DELETE_BOOK_HOTEL = """ This endpoint delete booking hotel """
GET_BOOK_HOTEL = """ This endpoint get booking hotel """
SORT_DESCRIPTION = """ Filter by sort """
